DROP DATABASE IF EXISTS food_delivery;
CREATE DATABASE food_delivery;
USE food_delivery;

CREATE TABLE Delivery_Status(
StatusID INT PRIMARY KEY AUTO_INCREMENT,
CurrentStatus VARCHAR(30)
);

CREATE TABLE Delivery_Personnel(
EmployeeID INT PRIMARY KEY AUTO_INCREMENT,
DelivererName VARCHAR(50) NOT NULL,
Username VARCHAR(20) NOT NULL,
DelivererPassword VARCHAR(50) NOT NULL,
PhoneNumber VARCHAR(30) NOT NULL,
Email VARCHAR(50) NOT NULL,
Capacity INT NOT NULL
);

CREATE TABLE Location(
LocationID INT PRIMARY KEY AUTO_INCREMENT,
Address VARCHAR(50) NOT NULL
);

CREATE TABLE Customer(
CustomerID INT PRIMARY KEY AUTO_INCREMENT,
CustomerName VARCHAR(50) NOT NULL,
Username VARCHAR(20) NOT NULL,
CustomerPassword VARCHAR(50) NOT NULL,
LocationID INT NOT NULL,
PhoneNumber VARCHAR(30) NOT NULL,
Email VARCHAR(50) NOT NULL,
DateOfBirth date,
FOREIGN KEY (LocationID) REFERENCES Location(LocationID)
);

CREATE TABLE Business(
BusinessID INT PRIMARY KEY AUTO_INCREMENT,
BusinessName VARCHAR(50) NOT NULL,
Username VARCHAR(20) NOT NULL,
BusinessPassword VARCHAR(50) NOT NULL,
Cuisine VARCHAR(50),
PhoneNumber VARCHAR(30) NOT NULL,
LocationID INT NOT NULL,
FOREIGN KEY (LocationID) REFERENCES Location(LocationID)
);

CREATE TABLE DatabaseAdmin(
AdminID INT PRIMARY KEY AUTO_INCREMENT,
AdminName VARCHAR(50) NOT NULL,
Username VARCHAR(20) NOT NULL,
AdminPassword VARCHAR(50) NOT NULL
);

CREATE TABLE Payment_Method(
	PaymentID INT PRIMARY KEY AUTO_INCREMENT,
	PaymentMethod VARCHAR(30) NOT NULL
);

CREATE TABLE Orders(
OrderID INT PRIMARY KEY AUTO_INCREMENT,
CustomerID INT NOT NULL,
BusinessID INT NOT NULL,
PaymentID INT NOT NULL,
OrderDate TIMESTAMP NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
ON DELETE RESTRICT,
FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID)
ON DELETE RESTRICT,
FOREIGN KEY (PaymentID) REFERENCES Payment_Method(PaymentID)
ON DELETE RESTRICT
);

CREATE TABLE Delivery(
	DeliveryID INT PRIMARY KEY AUTO_INCREMENT,
	OrderID INT NOT NULL,
	EmployeeID INT NOT NULL,
	LocationID INT,
	StatusID INT NOT NULL,
	DeliveryFee DECIMAL(5,2) NOT NULL,
	FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
ON DELETE CASCADE,
	FOREIGN KEY (EmployeeID) REFERENCES Delivery_Personnel (EmployeeID)
ON DELETE RESTRICT,
FOREIGN KEY (LocationID) REFERENCES Location(LocationID),
FOREIGN KEY (StatusID) REFERENCES Delivery_Status(StatusID)
);

CREATE TABLE Menu(
	MenuID INT PRIMARY KEY AUTO_INCREMENT,
BusinessID INT NOT NULL,
MenuName VARCHAR(30) NOT NULL,
FOREIGN KEY (BusinessID) REFERENCES Business(BusinessID)
ON DELETE RESTRICT
);

CREATE TABLE Menu_Item(
	ItemID INT PRIMARY KEY AUTO_INCREMENT,
MenuID INT NOT NULL,
ItemName VARCHAR(50) NOT NULL,
ItemPrice DECIMAL(10,2) NOT NULL,
Availability BOOLEAN,
FOREIGN KEY (MenuID) REFERENCES Menu(MenuID)
ON DELETE CASCADE
);

CREATE TABLE Order_Item(
	OrderID INT NOT NULL,
ItemID INT NOT NULL,
Quantity INT NOT NULL,
PRIMARY KEY (OrderID, ItemID),
FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
ON DELETE CASCADE,
FOREIGN KEY (ItemID) REFERENCES Menu_Item(ItemID)
ON DELETE RESTRICT
);
